### ISSUE TITLE
Document management of recipes in DX via the CLI + admin permissions

### ISSUE THREAD

**Issue by okundzich** [moderneinc/moderne-docs#107]
however, we don’t have documentation on how to manage recipes in DX and permissions for admin users to do so, only this. At the same time, we recommend using the CLI to Dov to manage the catalog

[Slack Message](https://moderneinc.slack.com/archives/C02KMK84DD2/p1718977610275279?thread_ts=1718977497.484539&cid=C02KMK84DD2)

**Comment by mike-solomon** [comment]
I believe @bryceatmoderne fixed this issue by updating this doc: https://docs.moderne.io/administrator-documentation/moderne-dx/how-to-guides/deploying-recipe-artifacts-in-moderne-dx

Resolving (but feel free to reopen if I misunderstood).
