### ISSUE TITLE
Add CLI FAQ entry on `! Failed to apply patch: Cannot apply: HunkHeader[47,7->47,7]`

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/moderne-docs#113]
From time to time folks can have [issues applying a patch file](https://moderneinc.slack.com/archives/C01S4M53THT/p1720447226670239) through `mod git apply`.

The error would look something like
```
> openrewrite/rewrite@main
    Applying patch file:///C:/Users/brycetompkins/it-reproduction/openrewrite/rewrite/.moderne/run/20240708101645-qEm3Y/fix.patch
    ! Failed to apply patch: Cannot apply: HunkHeader[44,7->44,7]
> openrewrite/rewrite-ai-search@main
    Applying patch file:///C:/Users/brycetompkins/it-reproduction/openrewrite/rewrite-ai-search/.moderne/run/20240708101645-qEm3Y/fix.patch
    ! Failed to apply patch: Cannot apply: HunkHeader[47,7->47,7]
```

There can be a number of causes, such as for instance conflicting changes on the target files; in those cases it could help to first commit/stash/revert the unsaved changes on the target repository, before running `mod git apply` again.

If the problem persists there might then be a bigger underlying issue, like a failure to handle a particular file encoding; in those cases it's best to contact support@moderne.io with the details contained in the fix.patch file and the target files, ideally reduced to the minimum needed to replicate the issue.

**Comment by timtebeek** [comment]
Note that we do **not** recommend or require a new LST build between every recipe run; as long as the changes from various recipe runs do not overlap the same lines on the same files, you should be able to stack applied changes. Once changes do start to overlap, it might make sense to commit those changes to separate branches and work with our IDE or SCM system to resolve the conflicts, or make the recipes part of the same recipe run, to avoid any such conflicts.

**Comment by mike-solomon** [comment]
@timtebeek In looking over that thread - it looks like this may be a CLI bug. Do you think it's still worth documenting this if that's the case?

If so, is the basic summary, "If you run into this issue, reset stuff and try again"?

**Comment by timtebeek** [comment]
> @timtebeek In looking over that thread - it looks like this may be a CLI bug. Do you think it's still worth documenting this if that's the case?
> If so, is the basic summary, "If you run into this issue, reset stuff and try again"?

We also see this when there are conflicts between the files on disk and when the LST was built; or even when the `git` executable we delegate to similarly fails to apply a patch file. Might help to answer questions to have at least something here to have folks troubleshoot themselves before reaching out if needed.
