### ISSUE TITLE
Update the recipe-builder documentation page to use the v2 builder

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/moderne-docs#115]
We document the old builder on this page:
https://docs.moderne.io/user-documentation/moderne-platform/how-to-guides/recipe-builder
https://github.com/moderneinc/moderne-docs/blob/8b2d0c2f42828bd9a1040d8abe9ffabced6e0d4b/user-documentation/moderne-platform/how-to-guides/recipe-builder.md?plain=1#L1-L7

The new builder is significantly different, and offers easier navigation & customization of recipe hierarchies:
https://www.moderne.ai/blog/moderne-engineering-building-the-openrewrite-recipe-builder

Best to update this doc page to reflect the shift towards the new builder.

**Comment by mike-solomon** [comment]
I've been holding off on documenting this based on feedback from Kevin that things are still in motion and may still change. Once things have settled and we figured out the plan, I'll work on this documentation.

**Comment by mike-solomon** [comment]
The new recipe builder has been documented here: https://docs.moderne.io/user-documentation/moderne-platform/how-to-guides/new-recipe-builder

Keeping the old one for now as it still exists - but once we remove it I'll clean up that doc. I believe I can resolve this issue for now. Feel free to reopen if you disagree or if I missed something.
