### ISSUE TITLE
Design announcement banner

### ISSUE THREAD

**Issue by mike-solomon** [moderneinc/moderne-docs#146]
Right now, at the top of our docs, we have an announcement banner for the code remix summit:

![Image](https://github.com/user-attachments/assets/c6e43294-d383-4844-84e0-d5f02823143b)

Jonathan requested that we improve the colors of this. I can update the text color, background color, and I can add HTML inside of it to change the colors of the individual letters such as in: 

![Image](https://github.com/user-attachments/assets/a6f5c76e-890a-4432-930b-aea40d85619d)

Related Slack thread: https://moderneinc.slack.com/archives/C045V3G92K1/p1730388453381589

**Comment by LindsayAuch** [comment]
@mike-solomon 

Taking the gradient background from the branding and applying that to the background color. 
https://docs.google.com/presentation/d/1yi8Ld7rwEPreu-07V7X9CSROFdJfdPypsEWlwb9UT4k/edit?usp=sharing



<img width="548" alt="Screenshot 2024-11-04 at 2 43 33 PM" src="https://github.com/user-attachments/assets/cfdc04be-ddc6-4370-a3cb-cd84b6cad234">

Hex #44A0DB and  #194EFD


<img width="240" alt="Screenshot 2024-11-04 at 2 40 02 PM" src="https://github.com/user-attachments/assets/d1842c82-ecad-4c8d-91ef-f987bf6ce709">

See the example from this website that does the same background treatment
<img width="791" alt="Screenshot 2024-11-04 at 2 41 42 PM" src="https://github.com/user-attachments/assets/b82feb9f-cf18-4310-aa8a-157dd2766c23">

Example dark mode and light mode versions

<img width="725" alt="Screenshot 2024-11-04 at 2 38 18 PM" src="https://github.com/user-attachments/assets/d9b503bc-c7a9-4e4e-a5a1-849e80300323">

<img width="768" alt="Screenshot 2024-11-04 at 2 39 29 PM" src="https://github.com/user-attachments/assets/0adcc0d6-2fc4-4c1c-a30e-6bc59c3e31bc">

**Comment by mike-solomon** [comment]
@LindsayAuch Thanks for the suggestions!

Unfortunately, that is quite difficult to read and fails accessibility standards on the lighter end of the spectrum: https://webaim.org/resources/contrastchecker/

![image](https://github.com/user-attachments/assets/e2d3fe25-a758-4af0-a767-c2c98a76770c)

Can you please suggest some more accessible colors?

For perspective - here are the current colors which are fine:

![image](https://github.com/user-attachments/assets/1f35e442-4b70-417a-9055-b11f038650b9)

**Comment by LindsayAuch** [comment]
How about #b12ade and #2546f0? 

<img width="847" alt="Screenshot 2024-11-05 at 4 00 41 PM" src="https://github.com/user-attachments/assets/983c87aa-cccd-47a4-82d3-a3f1c6afb981">


https://venngage.com/tools/accessible-color-palette-generator
<img width="1322" alt="Screenshot 2024-11-05 at 4 01 20 PM" src="https://github.com/user-attachments/assets/4a779a3f-6560-46c6-ad8f-716e82fe5587">

<img width="724" alt="Screenshot 2024-11-05 at 4 05 21 PM" src="https://github.com/user-attachments/assets/24409fac-86ec-4656-baf1-6b1335b9d8d7">

<img width="748" alt="Screenshot 2024-11-05 at 4 05 43 PM" src="https://github.com/user-attachments/assets/8fac263a-af50-4371-85a0-2417b2624c9f">

**Comment by mike-solomon** [comment]
Thanks @LindsayAuch - that's much better.
