### ISSUE TITLE
Improve Agent Documentation

### ISSUE THREAD

**Issue by mike-solomon** [moderneinc/moderne-docs#18]
Taken from Kevin:

* We need to better explain what Artifactory/Maven configurations are used for. Artifactory configurations can be used for ASTs. Maven configurations can be used for ASTs or Recipes, but loading ASTs through Maven configuration requires turning indexing on in the Maven repository. Most repos have it off by default.
* (I think) we are missing any documentation of how to set up Hashicorp Vault with an agent, the docs say to put the encryption key directly in the agent configuration, but we do have integration with Hashicorp Vault.
* (I think) we are missing any documentation of what happens when the encryption key is rotated. We may even (:yikes:) be missing documentation on how our encryption/security works. we usually give them a document (?) that they can take to their security review which would be on our miro board. Ideally that would be inside of our [docs.moderne.io](http://docs.moderne.io/) but i am pretty sure it's not right now.
* [This](https://docs.moderne.io/references/create-api-access-tokens) is our documentation of moderne PATs. It doesn't explain the limitations of tokens other than "you can't do admin stuff with a token". Users can commit and view diffs using a PAT, but only if they've authenticated with their SCM through the UI in the preceding 8 hours.

**Comment by sjungling** [comment]
closing this for now re: https://github.com/moderneinc/moderne-docs/issues/39#issuecomment-1832407377
