### ISSUE TITLE
Add validation + troubleshooting to agent docs

### ISSUE THREAD

**Issue by mike-solomon** [moderneinc/moderne-docs#39]
for agent documentation <@U043XKLDKB8> I suggest adding a validation step that takes them to Modern UI and makes sure all these tools are connected. Perhaps there are troublshooting steps as well. (not urgent)

[Slack Message](https://moderneinc.slack.com/archives/C01S4M53THT/p1680114722381299)

**Comment by kmccarp** [comment]
@natedanner @mike-solomon I believe we have this covered now, both through the UI and through the startup connection checks. Let me know if there's anything else you think we should do here.
