### ISSUE TITLE
Add documentation about how to debug a recipe with the Moderne CLI

### ISSUE THREAD

**Issue by rpau** [moderneinc/moderne-docs#53]
There are several use cases that the Moderne CLI has been designed for. One of them is to debug recipes with existing LSTs in the platform. That use case/example should be added in the documentation

**Comment by mike-solomon** [comment]
@kmccarp I think we're in the same state of, "If someone has time to provide an example demonstrating this then a doc can be made." As it stands, I'm not too familiar with recipe development, what common mistakes people run into, and how the CLI might help them with those mistakes.

**Comment by sjungling** [comment]
@mike-solomon still the same as 5 months ago?

**Comment by mike-solomon** [comment]
@sjungling Ya i’m not sure if this even applies anymore as the intellij connections handle this so much better now.

**Comment by sjungling** [comment]
good enough to close for now
