### ISSUE TITLE
Add Windows documentation for CLI

### ISSUE THREAD

**Issue by mike-solomon** [moderneinc/moderne-docs#56]
@traceyyoshima mentioned that the commands in the Moderne CLI docs do not work for Windows users. We should update them to provide correct examples for Windows users.

**Comment by kmccarp** [comment]
@mike-solomon we might be in a better state now for this?

**Comment by mike-solomon** [comment]
Yep this is something we should do - will remove the blocked label.

**Comment by mike-solomon** [comment]
I feel like we should close this as the commands should work for Windows - and if they don’t we should call out specific ones and fix them.
