### ISSUE TITLE
Document SCM and other integrations and their versions

### ISSUE THREAD

**Issue by okundzich** [moderneinc/moderne-docs#59]
In our documentation, list out the versions of SCMs we support.

For GitHub Enterprise, we support X-Y
For Bitbucket Server / Data Center, we support back to version 5.1 (I believe)
For GitLab, we support X-Y
For Artifactory, we support X-Y

etc.

**Comment by kmccarp** [comment]
For Bitbucket Server / Data Center, we support back to 5.5. I'm not sure we know on the others.

**Comment by okundzich** [comment]
I'd prefer if we put some versions, so if a customer has older versions we would negotiate them upgrading rather than by default jumping to provide support.

**Comment by mike-solomon** [comment]
@kmccarp In that case, can you provide some general versions when you have time?

**Comment by kmccarp** [comment]
Bitbucket Server / Data Center 5.5
GitHub Enterprise 3.6.7

(will edit when I get the current GitLab version)

**Comment by kmccarp** [comment]
GitLab is v16.3.4

**Comment by mike-solomon** [comment]
Updated [the doc](https://docs.moderne.io/administrator-documentation/references/supported-scms) with the last version - resolving.
