### ISSUE TITLE
Many GraphQL examples are invalid

### ISSUE THREAD

**Issue by mike-solomon** [moderneinc/moderne-docs#62]
In the [Recipe execution and commits with the Moderne API doc](https://docs.moderne.io/user-documentation/recipe-execution-and-commits-with-graphql) many of the GraphQL examples do not work.

For example the [retrieve repositories with results](https://docs.moderne.io/user-documentation/recipe-execution-and-commits-with-graphql) gives me the following error: `Variables are invalid JSON: Expected double-quoted property name in JSON at position 35.`. 

It looks like many of the query params are also formatted incorrectly (such as missing trailing commas). It also looks like there are extra `{` in some cases such as in the query params [here](https://docs.moderne.io/user-documentation/recipe-execution-and-commits-with-graphql#verify-commit-job).

I'm not sure how to fix these and could use some help from the team to ensure this function as expected.

**Comment by kmccarp** [comment]
The first thing I notice -- JSON (by default) does not allow comments. A lot of these variable definitions have comments in them, which won't work in graphql's JSON.

**Comment by kmccarp** [comment]
In theory I've fixed all of this and requested a review: https://app.gitbook.com/o/-MEp_3EtccewzekKY8mZ/s/-MhFwm0iG8BFZKPYoFkH/~/changes/379/user-documentation/how-to-guides/recipe-execution-and-commits-with-graphql

**Comment by mike-solomon** [comment]
Thanks for taking a look at this! I've gone ahead and merged these changes. I'll assume that's good enough for now - so going to close this issue.
