### ISSUE TITLE
Replace `spring-hateoas-examples` in `moderne-cli-exercise.md` now that https://repo.spring.io/libs-snapshot is inaccessible

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/moderne-docs#84]
spring-hateoas-examples has not been updated for years by now, and as such fails to build as to the repositories it uses are no longer accessible after https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023/

https://github.com/moderneinc/moderne-docs/blob/f26a539a9af15b40062e0cd170d11af585b5162e/user-documentation/workshops/spring-boot-migration-workshop/moderne-cli-exercise.md?plain=1#L1632

```[tasklist]
### Tasks
- [ ] Replace `spring-hateoas-examples` with a Spring project that does build and shows meaning full recipe results
```

**Comment by timtebeek** [comment]
Potentially one of these could work
https://github.com/spring-projects/spring-data-couchbase
https://github.com/spring-projects/spring-data-relational
https://github.com/spring-projects/spring-data-rest
https://github.com/spring-projects/spring-data-mongodb
https://github.com/spring-projects/spring-data-cassandra
https://github.com/spring-projects/spring-data-ldap
https://github.com/spring-projects/spring-data-elasticsearch
https://github.com/spring-projects/spring-data-redis
https://github.com/spring-projects/spring-data-keyvalue
https://github.com/spring-projects/spring-data-neo4j
https://github.com/spring-projects/spring-data-jpa
https://github.com/spring-projects/spring-data-commons

**Comment by mike-solomon** [comment]
Fixed: https://github.com/moderneinc/moderne-organizations-multitenant/pull/55

resolving
