### ISSUE TITLE
Document how to attach an IntelliJ debugger to Moderne CLI recipe runs, to debug a recipe

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/moderne-docs#97]
We already have a page on the Moderne IntelliJ plugin, which right now is nested below the Moderne CLI pages. With the expanded scope there I think we can move that into it's own top level documentation page (soon).

Additionally it'd be nice to document how folks can attach a debugger to a Moderne CLI recipe run, through `mod run . --jvm-debug` as documented on https://docs.moderne.io/user-documentation/moderne-cli/cli-reference#options-78.

Steps are roughly
0. Download or build and LST for your target project
1. Set your recipe as the active recipe from the IDE
2. Set a breakpoint in your Recipe where you want it
3. Launch `mod run . --jvm-debug` on the target project
4. Create a debug run configuration
![image](https://github.com/moderneinc/moderne-docs/assets/1027334/71d4a671-b655-47d6-82cb-a9cbf6a0cd0f)
![image](https://github.com/moderneinc/moderne-docs/assets/1027334/386ea9b9-fa57-4400-b07e-93e302c95ac3)
5. Launch the debug run configuration to attach the debugger
6. Step through your recipe as needed to inspect prebuilt LSTs

**Comment by okundzich** [comment]
The latest version of the Intellij plugin (not release yet) has an integrated experience, so doing a lot of this will no longer be necessary.
